spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BoardTest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: asd1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true   # ← Hibernate 후 data.sql 실행

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

server:
  port: 8080
